### ISSUE TITLE
Use JuliaFormatter.jl?

### ISSUE THREAD

**Issue by pjrule** [mggg/GerryChainJulia#119]
I saw @InnovativeInventor used [JuliaFormatter.jl](https://github.com/domluna/JuliaFormatter.jl) in a recent PR. Maybe we should standarize across our codebase.

**Comment by InnovativeInventor** [comment]
We already do this to some degree. Tests won't pass unless it's formatted with JuliaFormatter (or more accurately, tests won't pass unless nothing is changed when JuliaFormatter is applied to the repo).

https://github.com/mggg/GerryChainJulia/blob/aa00c07c574f0325b037be1d40c873f5bef4e001/.github/workflows/test.yml#L25-L53

Pre-commit hooks would be a nice touch and make this easier for folks (if that's what you meant by standardize).

**Comment by pjrule** [comment]
Ah, whoops—I missed this! Cool!
