### ISSUE TITLE
Serialize score data in .jld

### ISSUE THREAD

**Issue by matthewkol186** [mggg/GerryChainJulia#28]
Currently, score data is saved to a JSON file. However, in #23 we introduce a new data type called `ChainScoreData`. The user will probably have a better experience if this could be saved in a binary format to preserve the type structure.

**Comment by matthewkol186** [comment]
Reading through [this](https://discourse.julialang.org/t/what-is-the-preferred-way-to-save-variables/21918/27), it appears that there's not a strong consensus about how to save variables yet. Julia comes with its own [serializer](https://docs.julialang.org/en/v1/stdlib/Serialization/) in the Standard library. It's fairly simple to use (just call `serialize` and `deserialize`), so I actually feel like we don't need to write it into the library ourselves. Users can just call:

`serialize(filename, chain_score_data)` and `deserialize(filename, chain_score_data)`. It's so short that I don't feel like there's much gained from us writing it, so I kind of want to punt on addressing this PR for now (maybe I can just update the documentation to mention `serialize`?) @bsuwal @pjrule what do you think?

**Comment by bsuwal** [comment]
I think that is reasonable. Let's keep this issue open until we add `serialize()` to the documentation.

**Comment by matthewkol186** [comment]
Added `serialize` to documentation!
