### ISSUE TITLE
Improve differentiation between scores that return nothing vs scores that return something

### ISSUE THREAD

**Issue by matthewkol186** [mggg/GerryChainJulia#30]
Some `AbstractScore`s are meant to return values that get stored in the object returned by `flip_chain` / `recom_chain`. Others are simply meant to run every time a proposal is accepted. These types of scores should be somehow clearly delineated in our codebase, rather than manually checking if the return type is `nothing`, which gets quite expensive. 
Options I'm thinking about:
- In `score_initial_partition`, we can mark scores that return nothing on their first evaluation as having no return type. We can use that information for every subsequent proposal to automatically ignore anything returned by those scores, rather than manually checking
- Add a field to each `AbstractScore` class called `write_return` where the user can specify whether they want the object returned by the score to be written to the `ChainScoreData` object
- Scores that are initialized without a `name` field should not be written into the `ChainDataScore` object. **This feels nice & simple & easy to understand, and has the added benefit of not requiring us to create names for scores whose only function is to run and not to return any values**

Additional considerations:
- Think about `get_score_values`. Does any part of this need to be rewritten?

**Comment by bsuwal** [comment]
I really like the third one!

**Comment by matthewkol186** [comment]
Resolved in PR #39
