### ISSUE TITLE
Contribution guidelines 

### ISSUE THREAD

**Issue by NitinBhasneria** [mggg/GerryChainJulia#8]
Hey, all as there is no guidelines given for the contributors. I opened this issue as a check in. Please provide some guideline here. Thanks. Also I want to ask that is @bsuwal is the mentor of this project?

**Comment by bsuwal** [comment]
Hey Nitin, 

This is a really fresh project so we are not at a stage to be accepting contributions yet (and hence the lack of contribution guidelines :) ) but we intend to be by the summer. The guidelines we provide [here](https://summerofcode.withgoogle.com/organizations/6751366837436416/) is our current application portal. We do not expect prior contributions for this project as part of our application.

Best,
Bhushan
