### ISSUE TITLE
Format code in every file

### ISSUE THREAD

**Issue by sunnymatt** [mggg/GerryChainJulia#98]
I've been noticing some issues with indentation/formatting in our files and I think there may be a pretty easy solution, as easy as going into every file and clicking this "Format Code" button in Atom.

![image](https://user-images.githubusercontent.com/5581093/103104412-fd5d0280-45f4-11eb-9683-13ec00d6a331.png)

**Comment by sunnymatt** [comment]
Wondering if we can get some kind of formatting check set up automatically using CI and [JuliaFormatter](https://github.com/domluna/JuliaFormatter.jl/)?

**Comment by InnovativeInventor** [comment]
@sunnymatt What about this: https://github.com/github/super-linter?

**Comment by sunnymatt** [comment]
> @sunnymatt What about something like this: https://github.com/github/super-linter?

Good idea - but I don't see Julia as one of the [languages with a supported linter](https://github.com/github/super-linter#supported-linters) ☹️ 🤔

**Comment by bsuwal** [comment]
Formatting check using CI sounds like a great idea! A quick Google search took me nowhere -- but I am all thumbs up for this idea.

**Comment by InnovativeInventor** [comment]
Closing this due to https://github.com/mggg/GerryChainJulia/issues/119.
